{{- $clusterDomain := default "cluster.local" .Values.clusterDomain}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mailman3.fullname" . }}-web
  labels:
    {{- include "mailman3.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "mailman3.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
  template:
    metadata:
    {{- with .Values.web.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "mailman3.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: web
    spec:
      {{- with .Values.web.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.web.podSecurityContext | nindent 8 }}
      volumes:
        - name: web-data
          persistentVolumeClaim:
            claimName: {{ include "web.claimName" . }}
      containers:
        - name: mailman-web
          securityContext:
            {{- toYaml .Values.web.securityContext | nindent 12 }}
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          env:
            - name: HYPERKITTY_API_KEY
              value: {{ .Values.hyperkittyApiKey | quote }}
            - name: SECRET_KEY
              value: {{ .Values.djangoSecretKey | quote }}
            - name: MAILMAN_REST_URL
              value: {{ printf "http://%s-core.%s.svc.%s:8001" (include "mailman3.fullname" .) .Release.Namespace $clusterDomain | quote }}
            - name: MAILMAN_REST_USER
              value: {{ .Values.rest.rest_username | default "restadmin" | quote }}
            - name: MAILMAN_REST_PASSWORD
              value: {{ .Values.rest.rest_password | default "restpass" | quote }}
            - name: POSTORIUS_TEMPLATE_BASE_URL
              value: {{ printf "http://%s-web.%s.svc.%s:80" (include "mailman3.fullname" .) .Release.Namespace $clusterDomain | quote }}
            {{- if .Values.ingress.enabled }}
            - name: SERVE_FROM_DOMAIN
              value: {{ .Values.hostname | quote }}
            {{- end }}
            - name: DATABASE_URL
              value: sqlite://///opt/mailman-web-data/mailmanweb.db
            - name: DATABASE_TYPE
              value: sqlite
            - name: MAILMAN_ADMIN_USER
              value: {{ .Values.admin.username | quote }}
            - name: MAILMAN_ADMIN_EMAIL
              value: {{ .Values.admin.email | quote }}
            {{- if .Values.smtp }}
            - name: SMTP_HOST
              value: {{ .Values.smtp | quote }}
            {{- else }}
            - name: SMTP_HOST
              value: {{ printf "%s-core.%s.svc.%s" (include "mailman3.fullname" .) .Release.Namespace $clusterDomain | quote }}
            {{- end }}
          args:
            - uwsgi
            - --ini
            - /opt/mailman-web/uwsgi.ini
            - --static-map
            - /static=/opt/mailman-web-data/static
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
#            httpGet:
#              path: /
#              port: http
#          readinessProbe:
#            httpGet:
#              path: /
#              port: http
          volumeMounts:
            - name: web-data
              mountPath: /opt/mailman-web-data
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
      {{- with .Values.web.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "mailman3.fullname" . }}-web
  labels:
    {{- include "mailman3.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    {{- include "mailman3.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
